name: Fedora RPM

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number && format('pr{0}', github.event.number) || github.ref }}
  cancel-in-progress: true

jobs:
  Fedora:
    name: Build on Fedora
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman
          podman pull fedora:40

      - name: Get source
        uses: actions/checkout@v3
        with:
          path: 'miracle-wm'

      - name: Build the rpm
        run: |
          chmod -R 755 miracle-wm
          {
              echo 'FROM fedora:rawhide'
              echo 'RUN dnf install -y mock mock-core-configs distribution-gpg-keys'
              echo 'COPY miracle-wm miracle-wm-0.1.0'
              echo 'RUN tar --create --file miracle-wm-0.1.0.tar.gz miracle-wm-0.1.0'
              echo 'RUN mock --no-bootstrap-image --isolation=simple --root=fedora-40-x86_64 --sources . --spec miracle-wm-0.1.0/rpm/miracle-wm.spec'
          } > podmanfile
          podman build --tag fedora40test -f ./podmanfile
