name: Snap Stable

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  snap-stable:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for version determination

      - id: build-snap
        name: Build the snap
        uses: canonical/actions/build-snap@release
        with:
          snapcraft-channel: stable
          review-opts: "--allow-classic"

      - name: Store the snap as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-snap.outputs.snap-name }}
          path: ${{ steps.build-snap.outputs.snap-path }}
